[package]
name = "jai"
version = "0.1.0"
edition = "2018"

[lib]
name = "jai"
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.2.1"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
