from jai.logger import log, Severity


class Flags:
    NeedsString = False
    NeedsIO = False


def preamble_edit(flags: Flags) -> str:
    preamble = "// This code was auto-generated by jai\n"

    if flags.NeedsIO:
        preamble += "#include <stdio.h>"

    if flags.NeedsString:
        preamble += "typedef char * string;"

    preamble += "\n\n"

    return preamble


def write(outfile: str, code: str, flags: Flags):
    preamble = preamble_edit(flags)
    with open(outfile, "w") as file:
        file.write(preamble)
        file.write(code)

    log(f"Wrote to {outfile}", Severity.Info)
